import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/antd.registry'
import '../styles/app.css'
import NextAuthWrapper from '@/lib/next.auth.wrapper'
import { CheckContextProvider } from '@/lib/check.wrapper'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NextJs by trung nguyen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <NextAuthWrapper>
            <CheckContextProvider>
             {children}
            </CheckContextProvider>
          </NextAuthWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
